Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -13,10 +13,14 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - name: Find Dockerfile
+      - name: Find Dockerfile from the root
         id: find_dockerfile
         run: |
-          DOCKERFILE_PATH=$(find . -name Dockerfile | head -n 1)  # Find the Dockerfile path
+          DOCKERFILE_PATH=$(find . -name Dockerfile -print -quit)  # Find the Dockerfile path from the root
+          if [ -z "$DOCKERFILE_PATH" ]; then
+            echo "Dockerfile not found"
+            exit 1
+          fi
           echo "Dockerfile found at: $DOCKERFILE_PATH"
           echo "DOCKERFILE_PATH=$DOCKERFILE_PATH" >> $GITHUB_ENV  # Set the environment variable
 
@@ -24,11 +28,7 @@ jobs:
         run: |
           DOCKERFILE_DIR=$(dirname "$DOCKERFILE_PATH")  # Get directory of Dockerfile
           cd "$DOCKERFILE_DIR" && pwd  # Change to that directory and print it
-          
-      - name: Log in to Docker Hub
-        run: |
-          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
-          
+
       - name: Build Docker image
         run: |
           cd "$DOCKERFILE_DIR"  # Ensure we're in the correct directory
